[workspace]
members = [
  "crates/holochain*",
  "crates/lair_keystore_manager",
  "crates/hc_launch/src-tauri",
  "src-tauri",
]
resolver = "2"

[workspace.dependencies]

holochain_client = "0.3.1"

holochain = { version = "0.1.7", features = ["sqlite-encrypted"] }

holochain_cli_sandbox = "0.1.7"
holochain_conductor_api = "0.1.7"
holochain_state = "0.1.7"
holochain_types = "0.1.7"
holochain_util = { version = "0.1.3", features = [ "pw" ] }
holochain_zome_types = "0.1.5"
hdk = "0.1.5"

lair_keystore_api = "0.3.0"

mr_bundle = "0.1.3"

devhub_types = { git = "https://github.com/holochain/devhub-dnas", branch = "holochain-v0.1.x-support" }

