[package]
name = "random"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "random"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

random_integrity = { workspace = true } 
